### ISSUE TITLE
你好的的项目编译 为什么会报错呢

### ISSUE THREAD

**Issue by fyang0728** [tancolo/angular2#1]
1. 编译时webpack会报错
2. 同样的问题 不管你是的项目  还是官网的 webpack配置都会报错
 报错如下
Module build failed: TypeError: Cannot read property 'exclude' of undefined
    at applyDefaults (F:\angular-webpack\node_modules\awesome-typescript-loader\src\instance.ts:266:72)
    at Object.ensureInstance (F:\angular-webpack\node_modules\awesome-typescript-loader\src\instance.ts:145:5)
    at compiler (F:\angular-webpack\node_modules\awesome-typescript-loader\src\index.ts:37:20)
    at Object.loader (F:\angular-webpack\node_modules\awesome-typescript-loader\src\index.ts:18:18)
 @ multi app

请问你使用的版本是什么呢？

**Comment by tancolo** [comment]
@fyang94  Sorry, 
这个小项目，最近变化很大， 有可能会导致webpack编译出现问题。现在就着手处理，力争让每一个ng子项目都可以使用。
So，先解决你的问题。
1） 请问你进入的是哪个ng文件夹？ng-starter-webpack 还是 ng-tour-of-heroes? 
2） 能否把你的package以及webpack.common.js展示一下？

**Comment by fyang0728** [comment]
1：ng-tour-of-heroes
下载你的项目什么操作都都没有做。编译时 webpack 会报错


2：根据ng2官网配置的webpack 配置如下

var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var helpers = require('./helpers');

module.exports = {
    entry: {
        polyfills: './src/polyfills.ts',
        vendor: './src/vendor.ts',
        app: './src/main.ts'
    },

    resolve: {
        extensions: ['', '.ts', '.js']
    },

    module: {
        loaders: [
            {
                test: /\.ts$/,
                loaders: ['awesome-typescript-loader', 'angular2-template-loader']
            },
            {
                test: /\.html$/,
                loader: 'html'
            },
            {
                test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
                loader: 'file?name=assets/[name].[hash].[ext]'
            },
            {
                test: /\.css$/,
                exclude: helpers.root('src', 'app'),
                loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
            },
            {
                test: /\.css$/,
                include: helpers.root('src', 'app'),
                loader: 'raw'
            }
        ]
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: ['app', 'vendor', 'polyfills']
        }),

        new HtmlWebpackPlugin({
            template: 'src/index.html'
        })
    ]
};

3：package.json 如下
{
  "name": "angular2-webpack",
  "version": "1.0.0",
  "description": "A webpack starter for Angular",
  "scripts": {
    "start": "webpack-dev-server --inline --progress --port 8080",
    "test": "karma start",
    "build": "rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail"
  },
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~2.2.0",
    "@angular/compiler": "~2.2.0",
    "@angular/core": "~2.2.0",
    "@angular/forms": "~2.2.0",
    "@angular/http": "~2.2.0",
    "@angular/platform-browser": "~2.2.0",
    "@angular/platform-browser-dynamic": "~2.2.0",
    "@angular/router": "~3.2.0",
    "core-js": "^2.4.1",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "@types/node": "^6.0.45",
    "@types/jasmine": "^2.5.35",
    "angular2-template-loader": "^0.4.0",
    "awesome-typescript-loader": "^2.2.4",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "html-loader": "^0.4.3",
    "html-webpack-plugin": "^2.15.0",
    "jasmine-core": "^2.4.1",
    "karma": "^1.2.0",
    "karma-jasmine": "^1.0.2",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "null-loader": "^0.1.1",
    "phantomjs-prebuilt": "^2.1.7",
    "raw-loader": "^0.5.1",
    "rimraf": "^2.5.2",
    "style-loader": "^0.13.1",
    "typescript": "^2.0.3",
    "webpack": "^1.13.0",
    "webpack-dev-server": "^1.14.1",
    "webpack-merge": "^0.14.0"
  }
}

**Comment by tancolo** [comment]
Hello, @fyang94  
我的这个问题，很好解决。 原因是package.json中的版本号前面使用了 `^`, `~`等符号，表示下载的时候是有可能是最新的版本，导致依赖包之间出现不匹配。
使用 `npm list --depth 0` 查看你下载的是什么版本以及是否有 'Peer Error'错误。

## 解决方法
除掉package.json中的所有符号，使用固定版本号即可， 亲测可用！
```
"dependencies": {
        "@angular/common": "2.0.1",
        "@angular/compiler": "2.0.1",
        "@angular/core": "2.0.1",
        "@angular/forms": "2.0.1",
        "@angular/http": "2.0.1",
        "@angular/platform-browser": "2.0.1",
        "@angular/platform-browser-dynamic": "2.0.1",
        "@angular/router": "3.0.1",
        "@angular/upgrade": "2.0.1",
        "angular-in-memory-web-api": "0.1.1",
        "bootstrap": "3.3.7",
        "core-js": "2.4.1",
        "reflect-metadata": "0.1.8",
        "rxjs": "5.0.0-beta.12",
        "zone.js": "0.6.25"
    },
    "devDependencies": {
        "angular2-template-loader": "0.4.0",
        "awesome-typescript-loader": "2.2.4",
        "css-loader": "0.23.1",
        "extract-text-webpack-plugin": "1.0.1",
        "html-loader": "0.4.3",
        "raw-loader": "0.5.1",
        "style-loader": "0.13.1",
        "html-webpack-plugin": "2.24.1",
        "ts-loader": "0.9.5",
        "typescript": "2.0.3",
        "typings": "1.4.0",
        "webpack": "1.13.3",
        "webpack-dev-server": "1.16.2"
    }

```
请暂时不要下载我github上的ng2-tour-of-heroes项目，在升级到angular@2.4.2过程中遇到问题，谢谢！
至于你说的参考官网上是wabpack打包例子，那个例子写的有点复杂，而且，其中的package.json也不是固定版本号，即使按照步骤来做，不保证正确，可以尝试固定版本号做法，解决官网webpack教程。
遇到问题，可以google，不建议baidu。
后续在本angualr2仓库中会添加各种webpack使用方法。
Enjoy yourself！

**Comment by fyang0728** [comment]
非常感谢
